name: CI
on:
  - push
  - pull_request
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - 'lts'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
        cache-scratchspaces: false #we want to test loading
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.version == 'lts' && matrix.os == 'ubuntu-latest'
      - uses: codecov/codecov-action@v4
        if: matrix.version == 'lts' && matrix.os == 'ubuntu-latest'
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}